import { Injectable } from '@angular/core';
import Cookies from 'js-cookie';

@Injectable({
  providedIn: 'root'
})
export class WindowAuthService {
  constructor() { }

  private generateRandomBuffer(length: number): Uint8Array {
    const randomBuffer = new Uint8Array(length);
    window.crypto.getRandomValues(randomBuffer);
    return randomBuffer;
  }

  // Registers a new credential (like a fingerprint or Face ID) for the user
  async register(email: string, password: string) {
    // Store email and password securely in cookies
    const studentId = 'some-unique-student-id'; // Generate a unique student ID
    Cookies.set('student_credentials', JSON.stringify({ email, password, studentId }), { expires: 7 }); // Expires in 7 days

    // Generate a unique challenge for the WebAuthn registration process
    const challenge = this.generateRandomBuffer(32);

    // PublicKeyCredentialCreationOptions is the core object needed for registration
    const publicKey: PublicKeyCredentialCreationOptions = {
      challenge: challenge, // A random value generated by the server to ensure the request is fresh and unique
      rp: { // Relying Party (your app) information
        name: "OurAwesomeApp" // Display name of your app
      },
      user: { // User information
        id: this.generateRandomBuffer(16), // A unique identifier for the user
        name: email,
        displayName: "Example User"
      },
      pubKeyCredParams: [
        { type: "public-key", alg: -7 },
        { type: "public-key", alg: -257 }
      ],
      authenticatorSelection: {
        authenticatorAttachment: "platform",
        userVerification: "required"
      },
      timeout: 60000,
      attestation: "direct"
    };

    try {
      const credential = await navigator.credentials.create({ publicKey }) as PublicKeyCredential;
      this.storeCredential(credential, challenge);
      console.log("Registration successful!", credential);
      return studentId;
    } catch (err) {
      console.error("Registration failed:", err);
      throw err;
    }
  }

  async authenticate(email: string, password: string) {
    // Retrieve stored credentials from cookies
    const storedCredentials = Cookies.get('student_credentials');
    if (!storedCredentials) {
      throw new Error("No stored credentials found. Please register first.");
    }

    const { storedEmail, storedPassword, studentId } = JSON.parse(storedCredentials);

    // Check if the provided email and password match the stored ones
    if (storedEmail !== email || storedPassword !== password) {
      throw new Error("Invalid email or password.");
    }

    // WebAuthn authentication
    const storedCredential = this.getStoredCredential();
    if (!storedCredential) {
      throw new Error("No stored credential found. Please register first.");
    }

    const publicKey: PublicKeyCredentialRequestOptions = {
      challenge: new Uint8Array(storedCredential.challenge),
      allowCredentials: [{
        id: new Uint8Array(storedCredential.rawId),
        type: "public-key"
      }],
      userVerification: "required",
      timeout: 60000
    };

    try {
      const credential = await navigator.credentials.get({ publicKey }) as PublicKeyCredential;
      console.log("Authentication successful!", credential);
      return { email, studentId: studentId };
    } catch (err) {
      console.error("Authentication failed:", err);
      throw err;
    }
  }

  private storeCredential(credential: PublicKeyCredential, challenge: Uint8Array) {
    const credentialData = {
      rawId: Array.from(new Uint8Array(credential.rawId)),
      challenge: Array.from(challenge)
    };
    localStorage.setItem('webauthn_credential', JSON.stringify(credentialData));
  }

  private getStoredCredential(): any {
    const storedCredential = localStorage.getItem('webauthn_credential');
    return storedCredential ? JSON.parse(storedCredential) : null;
  }
}
