import { Injectable } from '@angular/core';
import { AuthService } from '../API/Auth/auth.service';
import { Router } from '@angular/router';

@Injectable({
  providedIn: 'root'
})
export class WindowAuthService {

  constructor(private authService: AuthService , private rout:Router) { }

  private generateRandomBuffer(length: number): Uint8Array {
    const randomBuffer = new Uint8Array(length);
    window.crypto.getRandomValues(randomBuffer);
    return randomBuffer;
  }

  // Registers a new credential (like a fingerprint or Face ID) for the user
  async register(email: string, password: string) {

    // Generate a unique challenge for the registration process
    const challenge = this.generateRandomBuffer(32);

    // PublicKeyCredentialCreationOptions is the core object needed for registration
    const publicKey: PublicKeyCredentialCreationOptions = {
      challenge: challenge, // A random value generated by the server to ensure the request is fresh and unique
      rp: { // Relying Party (your app) information
        name: "OurAwesomeApp" // Display name of your app
      },
      user: { // User information
        id: this.generateRandomBuffer(16), // A unique identifier for the user
        name: email,
        displayName: "Way Makers "
      },
      pubKeyCredParams: [
        { type: "public-key", alg: -7 },
        { type: "public-key", alg: -257 }
      ],
      authenticatorSelection: {
        authenticatorAttachment: "platform",
        userVerification: "required"
      },
      timeout: 60000,
      attestation: "direct"
    };

    try {
      let auth = {
        email: email,
        password: password
      }

      const credential = await navigator.credentials.create({ publicKey }) as PublicKeyCredential;

      this.authService.signIn(auth).subscribe({
        next: (res: string) => {
          this.storeCredential(credential, challenge, password, email);
          console.log("Registration successful!", credential);
          return credential;
        }, error: () => {
             this.rout.navigate(['/bio'])
        }
      })

    } catch (err) {
      console.error("Registration failed:", err);
      throw err;
    }
  }

  async authenticate() {
    const storedCredential = this.getStoredCredential();
    console.log(storedCredential)
    if (!storedCredential) {
      throw new Error("No stored credential found. Please register first.");
    }

    const publicKey: PublicKeyCredentialRequestOptions = {
      challenge: new Uint8Array(storedCredential.challenge),
      allowCredentials: [{
        id: new Uint8Array(storedCredential.rawId),
        type: "public-key"
      }],
      userVerification: "required",
      timeout: 60000
    };

    try {

      const credential = await navigator.credentials.get({ publicKey }) as PublicKeyCredential;
      console.log("Authentication successful!", credential);
      let auth = {
        email: storedCredential.email,
        password: storedCredential.password
      }
      console.log(auth)
      this.authService.signIn(auth).subscribe({
        next: (res: string) => {
          localStorage.setItem('token', res)
        }, error: () => {

        }, complete: () => {
          console.log("User Login Successfull")
        }
      })
      return credential;
    } catch (err) {
      console.error("Authentication failed:", err);
      throw err;
    }
  }

  private storeCredential(credential: PublicKeyCredential, challenge: Uint8Array, password: string, email: string) {
    const credentialData = {
      rawId: Array.from(new Uint8Array(credential.rawId)),
      challenge: Array.from(challenge),
      email: email,
      password
    };
    localStorage.setItem('webauthn_credential', JSON.stringify(credentialData));
  }

  private getStoredCredential(): any {
    const storedCredential = localStorage.getItem('webauthn_credential');
    return storedCredential ? JSON.parse(storedCredential) : null;
  }
}
